name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: pip install beancount
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn global add vsce
      - run: yarn
      - run: yarn test
      - run: vsce package
